apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appName}}
type: Opaque
data:
  mongo_username: {{ .Values.otf.mongo.username | b64enc}}
  mongo_password: {{ .Values.otf.mongo.password | b64enc}}
  camunda_db_username: {{ .Values.otf.camunda.db.username | b64enc}}
  camunda_db_password: {{ .Values.otf.camunda.db.password | b64enc}}