# Default values for otf.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

shared: &shared
  # httpProxy: ""
  # httpsProxy: ""
  namespace: db
  # proxyUrl: ""
  # proxyPort: 3128
  nodeApi:
    url: ""
    host: ""

global:
        
  mongodb: &mongodb
    <<: *shared
    appName: mongodb
    version: Camille.2.1
    replicas : 1
    mongodbRootPassword: ""
    mongodbUsername: ""
    mongodbPassword: ""
    mongodbDatabase: otf
    port: 27017
    targetPort: 27017
    image:
      registry: docker.io
      repository: bitnami/mongodb
      tag: 4.2.6-debian-10-r18
      pullPolicy: IfNotPresent
      debug: false
    resources:
      limits:
        memory: "500Mi"
        cpu: "1"
      requests:
        memory: "256Mi"
        cpu: "1"
        
  mysqldb: &mysqldb
    <<: *shared
    appName: mysqldb
    version: Camille.2.1
    replicas : 1
    mysqlRootPassword: ""
    mysqlUser: ""
    mysqlPassword: ""
    mysqlDatabase: otf_camunda
    port: 3306
    targetPort: 8306
    image:
      registry: docker.io
      image: mysql
      tag: 5.7.26
      pullPolicy: IfNotPresent
      debug: false
    resources:
      limits:
        memory: "500Mi"
        cpu: "1"
      requests:
        memory: "256Mi"
        cpu: "1"

configurationFiles: 
  mysql.cnf: |-
    [mysqld]
    bind-address=0.0.0.0