appName: a1-policy-manager-vth
env: dev
version: 0.0.1-SNAPSHOT
image: image-registry
namespace:
nodePort: 32330
replicas: 1
health : /otf/vth/oran/a1/v1/health
sharedCert: otf-cert-secret-builder
pullSecret: "docker.secret"
pvc:
  dev: org-oran-otf-dev-logs-pv
  prod: org-oran-otf-prod-logs-pv
auth:
  enabled: true
  user: user
  pw: pw
proxy:
  enabled: false
  http: 
  # https: 
api:
  base_url: http://njcdtl08rg9907.itservices.sbc.com
  port: 3000
