apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appName}}
type: Opaque
data:
  id_private_key: {{ .Files.Get .Values.Secret.id_private_key | b64enc }}
  id_private_key_passphrase: {{ .Values.Secret.id_private_key_passphrase | b64enc }}