apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appName}}
type: Opaque
data:
  PKCS12_CERT: {{ .Files.Get .Values.Secret.PKCS12_CERT | b64enc }}
  PKCS12_KEY: {{ .Values.Secret.PKCS12_KEY | b64enc}}
  PEM_CERT: {{ .Files.Get .Values.Secret.PEM_CERT | b64enc}}
  PEM_KEY: {{ .Files.Get .Values.Secret.PEM_KEY | b64enc}}
  private_key: {{ .Files.Get .Values.Secret.privateKey.key | b64enc}}
  private_key_username:  {{ .Values.Secret.privateKey.username | b64enc}}
  private_key_passphrase: {{ .Values.Secret.privateKey.passphrase | b64enc}}
