apiVersion: v2
name: one-click-vhts
description: A Helm chart for one click  vth deploymeny 

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
#type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
#version: 0.1.0
version: 0.0.1

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application.
#appVersion: 1.16.0
appVersion: "1.0"

dependencies:
- name: a1-mediator-vth
  version: 0.0.1
  repository: "file://../../a1-mediator-vth/helm/a1-mediator-vth/"
- name: a1-policy-manager-vth
  version: 0.0.1
  repository: "file://../../a1-policy-manager-vth/helm/a1-policy-manager-vth/"
- name: a1-sdnc-vth
  version: 0.0.1
  repository: "file://../../a1-sdnc-vth/helm/a1-sdnc-vth/"
- name: dmaap-vth
  version: 0.0.1
  repository: "file://../../dmaap-vth/helm/dmaap-vth/"
- name: otf-ping-test-head
  version: 0.0.1
  repository: "file://../../otf-ping-test-head/helm/otf-ping-test-head/"
- name: oran-ric-test-head
  version: 0.0.1
  repository: "file://../../oran-ric-test-head/helm/ric-test-head/"
- name: otf-ssh-test-head
  version: 0.0.1
  repository: "file://../../otf-ssh-test-head/helm/otf-ssh-test-head/"
- name: smo-o1-vth
  version: 0.0.1
  repository: "file://../../smo-o1-vth/helm/smo-o1-vth/"
- name: otf-robot-test-head
  version: 0.0.5-SNAPSHOT
  repository: "file://../../otf-robot-test-head/helm/otf-robot-test-head/"
