apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appName}}
type: Opaque
data:
  mongo_username: {{ .Values.otf.mongo.username | b64enc}}
  mongo_password: {{ .Values.otf.mongo.password | b64enc}}