appName: otf-camunda
version: 0.0.1-SNAPSHOT
image: otf-camunda:0.0.1-SNAPSHOT
namespace: org.oran.otf
nodePort: 31313
replicas: 2
terminationGracePeriodSeconds: 360
env: dev

# Environment variables for the service api.
otf:
  mongo:
    dev:
      host: localhost:27017,localhost:27017,localhost:27017
      replicaSet: mongoOTF
      database: otf
    st:
      host: localhost:27017,localhost:27017,localhost:27017
      replicaSet: mongoOTF
      database: otf_st
    prod:
      host: localhost:18720,localhost:18720,localhost:18720
      replicaSet: otf-rs-prod2
      database: otf
    username: "test"
    password: "test"
  camunda:
    executors_active:
      dev: true
      st: true
      prod: false
      prod_dr: true
    tcu:
      port: 8443
    db:
      dev:
        url: localhost:3306/otf-camunda
      st:
        url: localhost:3306/otf_st-camunda
      prod:
        url: localhost:3306/otf-camunda
      username: username
      password: password
    router:
      config:
        dev: mysqlRouterConfig-dev.ini
        st: mysqlRouterConfig-st.ini
        prod: mysqlRouterConfig-prod.ini
      image: mysql/mysql-router
      port: 3306
# permission type for aaf
aafPermType:
  dev: org.oran.otf.dev.camunda
  st: org.oran.otf.st.camunda   
  prod: org.oran.otf.prod.camunda

cadiHostname:
  dev: localhost
  st: localhost
  prod: localhost
  prod_dr: localhost

  
# Secret related information.
sharedSecret: otf-aaf-credential-generator
sharedCert: otf-cert-secret-builder
cert:
  dev: 
    name: otf_dev.p12
    path: opt/cert/otf_dev.p12
  st: 
    name: otf_st.p12
    path: opt/cert/otf_st.p12
  prod: 
    name: otf_prod.p12
    path: opt/cert/otf_prod.p12

Secret:
  privateKey:
    name: key.key
    path: opt/cert/key.key

pvc:
  dev: org-oran-otf-dev-logs-pv
  prod: org-oran-otf-prod-logs-pv

