appName: otf-frontend
version: 0.0.4-SNAPSHOT
pullSecret: "docker.secret"
image: image-registry
namespace: 
nodePort: 32524
replicas:
  dev: 2
  st: 1
  prod: 2
env: dev
AUTHENTICATION_SECRET: ""
serviceApi:
  prod:
    SERVICEAPI_URL: "https://localhost:32303/otf/api/"
    SERVICEAPI_URIEXECUTETESTINSTANCE: "testInstance/execute/v1/id/"
  prod_dr:
    SERVICEAPI_URL: "https://localhost:32303/otf/api/"
    SERVICEAPI_URIEXECUTETESTINSTANCE: "testInstance/execute/v1/id/" 
  st:
    SERVICEAPI_URL: "https://localhost:32303/otf/api/"
    SERVICEAPI_URIEXECUTETESTINSTANCE: "testInstance/execute/v1/id/"
  dev:
    SERVICEAPI_URL: "https://localhost:32303/otf/api/"
    SERVICEAPI_URIEXECUTETESTINSTANCE: "testInstance/execute/v1/id/"
camundaApi:
  prod:
    CAMUNDAAPI_URL: "https://localhost:31313/"
  prod_dr:
    CAMUNDAAPI_URL: "https://localhost:31313/"
  st:
    CAMUNDAAPI_URL: "https://localhost:31313/"
  dev:
    CAMUNDAAPI_URL: "https://localhost:31313/"
mongo:
  prod:
    MONGO_BASEURL: "localhost:27017/"
    MONGO_DBOTF: "otf"
    MONGO_REPLICASET: "rs0"
  st:
    MONGO_BASEURL: "localhost:27017"
    MONGO_DBOTF: "otf_st"
    MONGO_REPLICASET: "rs0"
  dev:
    MONGO_BASEURL: "localhost:27017"
    MONGO_DBOTF: "otf"
    MONGO_REPLICASET: "rs0"
  username: "!"
  password: "!"
otf:
  OTF_EMAIL: "OTF_NO-REPLY@localhost.com"
  OTF_URL:
    dev: "https://localhost:32524/"
    st: "https://localhost:32524/"
    prod: "https://localhost:32524/"

sharedSecret: otf-aaf-credential-generator
sharedCert: otf-cert-secret-builder

healthEndpoint: otf/api/health/v1

one_click:
  enabled: false
  mongo:
    replicaset: rs0
    database: otf
    secret_name: mongo-mongodb
    ip: 10.0.51.84:27017
    username: "!"
    password: "!"
