appName: otf-oran-service-api
version: latest
pullSecret: "docker.secret"
image: image-registry
namespace: 
nodePort: 32303
replicas:
  dev: 2
  st: 1
  prod: 2
env: dev
# Environment variables for the service api.
otf:
  mongo:
    dev:
      host: 127.0.0.1:27017
      replicaSet: rs0
      database: otf
    st:
      host: localhost:27017,localhost:27017,localhost:27017
      replicaSet: ""
      database: ""
    prod:
      host: localhost:18720,localhost:18720,localhost:18720
      replicaSet: ""
      database: ""
    username: "!"
    password: "!"
  camunda:
    dev:
      host: https://localhost
      port: 31313
    st:
      host: https://localhost
      port: 31313
    prod:
      host: https://localhost
      port: 31313
    prod_dr:
      host: https://localhost
      port: 31313
    uri:
      process_definition: rest/process-definition/key
      delete_test_strategy: otf/tcu/delete-test-strategy/v1/deployment-id
      delete_test_strategy_test_definition_id: otf/tcu/delete-test-strategy/v1/test-definition-id
      execute_test: otf/tcu/execute/workflowRequest
      deploy_test_strategy_zip: otf/tcu/deploy-test-strategy-zip/v1
      process_instance_completion_check: otf/tcu/process-instance-completion-check/v1
      health: /otf/health/v1
    executionUri: otf/tcu/execute-test/v1
    pollingUri: otf/tcu/process-instance-completion-check/v1
    deploymentUri: otf/tcu/deploy-test-strategy-zip/v1
    processDefinitionKeyUri: rest/process-definition/key
    deploymentDeletionUri: otf/tcu/delete-test-strategy/v1/deployment-id
    testDefinitionDeletionUri: otf/tcu/delete-test-strategy/v1/test-definition-id
  api:
    poll_interval: 6000
    poll_attempts: 50

# permission type for aaf
aafPermType:
  dev: ""
  st:  ""
  prod:  ""

cadiHostname:
  dev: localhost
  st: localhost
  prod: localhost
  prod_dr: localhost
  
# Secret related information.
sharedSecret: otf-aaf-credential-generator
sharedCert: otf-cert-secret-builder
cert:
  dev: 
    name: ""
    path: ""
  st: 
    name: ""
    path: ""
  prod: 
    name: ""
    path: ""
  
pvc:
  dev: ""
  prod: ""

one_click:
  enabled: false
  mongo:
    replicaset: "!"
    database: "!"
    secret_name: mongo-mongodb
    ip: 127.0.0.1:27017
    username: "!"
    password: "!"
